### ISSUE TITLE
Trajectory acquisition by fusing camera and IMU

### ISSUE THREAD

**Issue by zhouxu-github** [pvangoor/eqvio#2]
Hello, thank you for your dedication to providing this code. Now the output is only the camera trajectory, how do I get the final filtered trajectory fused with the camera and IMU?

**Comment by pvangoor** [comment]
Hi, I am not sure what your problem is. When I run it myself using this command:
`./build/eqvio_opt /home/pieter/datasets/V1_01_easy/ configs/EQVIO_config_EuRoC_stationary.yaml --display --mode asl`
the code creates a new directory called "EQVIO_output_DATE_TIME" in the current working directory. It contains several csv files including the IMU state and the camera offset. If you wish to recover the camera state, you only have to multiply the IMU state by the camera offset.

**Comment by zhouxu-github** [comment]
Thank you for your prompt reply! I ran the same command for the EuRoc dataset and generated a folder, but the only files in the folder were: For these files, biass.csv, camera.csv, features.csv, IMUState.csv and points.csv, the final generated trajectory file is not found. Because I want to use this method you proposed to compare with other VIO methods.

**Comment by pvangoor** [comment]
The IMUState.csv contains the trajectory of the IMU (body) frame, expressed as time, position (xyz), quaternion (wyz), body-fixed velocity (xyz).

**Comment by zhouxu-github** [comment]
Thanks for your timely help, I have solved this problem, and further understand the importance of your work!
